export const ERROR_CODES = Object.freeze({
	NOT_IMPLEMENTED: 'NOT_IMPLEMENTED',
	NOT_FOUND: 'NOT_FOUND',
	VALIDATION_ERROR: 'VALIDATION_ERROR',
	UNAUTHORIZED: 'UNAUTHORIZED',
	FORBIDDEN: 'FORBIDDEN',
	INTERNAL_ERROR: 'INTERNAL_ERROR'
});

/** Códigos de resultado de `POST /api/v1/saren/verify-stamp` (Módulo 06). */
export const STAMP_VERIFICATION_CODES = Object.freeze({
	NOT_FOUND: 'NOT_FOUND',
	ALREADY_USED: 'ALREADY_USED',
	ANNULLED: 'ANNULLED',
	VALIDATED_AND_CONSUMED: 'VALIDATED_AND_CONSUMED'
});
